version: '2'

services:
  frontend:
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile
    ports:
     - 80:80
  backend:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    ports:
     - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/todo-list-web-app?schema=public
      - PORT=3000
  postgres:
    image: postgres
    ports:
     - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo-list-web-app
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data